branches:
  - main
  - { name: beta, prerelease: true, channel: beta }
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@google/semantic-release-replace-plugin'
    - replacements:
        - files:
            - build.sbt
          from: version := .*
          to: version := "${nextRelease.version}"
          results:
            - file: build.sbt
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - package.json
          from: '\"version\": \".*\"'
          to: '"version": "${nextRelease.version}"'
          results:
            - file: package.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - package-lock.json
          from: '\"name\": \"lambdas-as-a-service\",\n  \"version\": \".*\"'
          to: "\"name\": \"lambdas-as-a-service\",\n  \"version\": \"${nextRelease.version}\""
          results:
            - file: package-lock.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - package-lock.json
          from: '\"name\": \"lambdas-as-a-service\",\n      \"version\": \".*\"'
          to: "\"name\": \"lambdas-as-a-service\",\n      \"version\": \"${nextRelease.version}\""
          results:
            - file: package-lock.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - sonar-project.properties
          from: sonar.projectVersion=.*
          to: sonar.projectVersion=${nextRelease.version}
          results:
            - file: sonar-project.properties
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - - '@semantic-release/exec'
    - publishCmd: |
        sbt tsServer/assembly;
        sbt tsServer/dockerBuildAndPush;
        sbt worker/assembly;
        sbt worker/dockerBuildAndPush;
        cd ui;
        npm install;
        npm run build;
        cd ..;
        sbt master/assembly;
        sbt master/dockerBuildAndPush;
      shell: /bin/bash
  - - '@semantic-release/git'
    - assets:
        - build.sbt
        - README.md
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - sonar-project.properties
  - - '@semantic-release/github'
    - assets:
        - path: server/target/scala-3.3.0/main.jar
          name: ts-server.jar
          label: TS Server JAR file
        - path: worker/target/scala-3.3.0/main.jar
          name: worker.jar
          label: Worker JAR file
        - path: master/target/scala-3.3.0/main.jar
          name: master.jar
          label: Master JAR file