version: "3.9"

services:
  tuplespace:
    image: "matteocastellucci3/laas-ts-server:latest"
    build: ./server
    expose:
      - 80
    hostname: tuplespace
    environment:
      - TUPLES_SPACE_PORT_NUMBER=80
      - TUPLES_SPACE_SERVICE_PATH=tuplespace
    healthcheck:
      test: ["CMD", "curl", "http://tuplespace/tuplespace"]
      interval: 10s
      timeout: 60s
      start_period: 10s
      start_interval: 3s
  postgres:
    image: "postgres:16.0"
    expose:
      - 5432
    hostname: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=laas

  first_worker:
    image: "matteocastellucci3/laas-worker:latest"
    build: ./worker
    depends_on:
      tuplespace:
        condition: service_healthy
    environment:
      - WORKER_ID=bdd00fa6-db48-4b08-8b3c-488a1795f1c5
      - WORKER_TS_URI=ws://tuplespace/tuplespace
      - WORKER_HTTP_CLIENT_URI=http://master/service/files
      - WORKER_ACCEPTED_EXECUTABLES=Java;Python
      - WORKER_AVAILABLE_SLOTS=100
      - WORKER_BUFFER=100
    volumes:
      - worker1_volume:/executables
  second_worker:
    image: "matteocastellucci3/laas-worker:latest"
    build: ./worker
    depends_on:
      tuplespace:
        condition: service_healthy
    environment:
      - WORKER_ID=17439dad-d9ed-4ee6-af05-7eca427ae025
      - WORKER_TS_URI=ws://tuplespace/tuplespace
      - WORKER_HTTP_CLIENT_URI=http://master/service/files
      - WORKER_ACCEPTED_EXECUTABLES=Java;Python
      - WORKER_AVAILABLE_SLOTS=100
      - WORKER_BUFFER=100
    volumes:
      - worker2_volume:/executables
  master:
    image: "matteocastellucci3/laas-master:latest"
    build: ./master
    expose:
      - 80
    ports:
      - "8080:80"
    hostname: master
    depends_on:
      tuplespace:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      - MASTER_TS_URI=ws://tuplespace/tuplespace
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=laas
      - DB_PORT_NUMBER=5432
      - DB_HOSTNAME=postgres
      - DB_TIMEOUT=30000
      - MASTER_BUFFER=100
      - MASTER_PORT_NUMBER=80

volumes:
  worker1_volume:
  worker2_volume: